### ISSUE TITLE
Single version in repo_overview CALIBRATED_MODEL

### ISSUE THREAD

**Issue by oksanapavliuk** [pailabteam/pailab#101]
Jupyter notebook: home_loans_credit_default

Only one model version in repo_overview is displayed. Multiple versions are expected.
![image](https://user-images.githubusercontent.com/50184402/85296114-2e6f4580-b4a1-11ea-9c7e-6433333a7c7e.png)

**Comment by favdo** [comment]
The _ObjectOverviewList_ widget shows only the objects contained in the repo and not the history of each object. Just try out the _ObjectView_ widget, that should show you the history of objects.
